spring.application.name=escola-projeto
server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5433/escola_exercicio
spring.datasource.username=postgres
spring.datasource.password=159753
spring.datasource.driver-class-name=org.postgresql.Driver

spring.datasource.testWhileIdle=true
spring.datasource.validationQuery=SELECT 1

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
